### ISSUE TITLE
File not found:  iODBC/sqltypes.h

### ISSUE THREAD

**Issue by Oleg26Dev** [openlink/iODBC#28] opened 2018-02-14 07:04 UTC
My app does
#include <sql.h>

but during the compilation I receive the error: file not found:  iODBC/sqltypes.h
It means: sql.h includes 
#include <iODBC/sqltypes.h>

But this file located in the same directory as sql.h
May be need to
#include <sqltypes.h> ?

**Comment by smalinin** [comment] 2018-02-14 11:10
Duplicate of https://github.com/openlink/iODBC/issues/27
Use properly building steps in https://github.com/openlink/iODBC/blob/develop/README_MACOSX.md#method-1-using-project-builder
and files will be created.

**Closed by smalinin** 2018-02-14 11:10 UTC
